include(FindPkgConfig)
if (PKG_CONFIG_FOUND)
    if (GLIB_FIND_REQUIRED)
        set(_PACKAGE_ARGS REQUIRED)
    else ()
        set(_PACKAGE_ARGS "")
    endif ()
    pkg_check_modules(GTK2 gtk+-2.0 ${_PACKAGE_ARGS})
endif ()
