include(FindPkgConfig)
if (PKG_CONFIG_FOUND)
    if (Minizip_FIND_REQUIRED)
        set(_PACKAGE_ARGS REQUIRED)
    else ()
        set(_PACKAGE_ARGS "")
    endif ()
    pkg_check_modules(Minizip minizip ${_PACKAGE_ARGS})
endif ()
