include(FindPkgConfig)
if (PKG_CONFIG_FOUND)
    if (GLIB_FIND_REQUIRED)
        set(_PACKAGE_ARGS REQUIRED)
    else ()
        set(_PACKAGE_ARGS "")
    endif ()
    if (XWINDOWS)
        pkg_check_modules(GTKGL gtkglext-x11-1.0 ${_PACKAGE_ARGS})
    elseif (WIN32)
        pkg_check_modules(GTKGL gtkglext-win32-1.0 ${_PACKAGE_ARGS})
    else ()
        pkg_check_modules(GTKGL gtkglext-quartz-1.0 ${_PACKAGE_ARGS})
    endif ()
endif ()
